In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array((1,2,3,4))
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [3]:
c=np.array([[1,2,3],[3,4,'n']])
print(c)

[['1' '2' '3']
 ['3' '4' 'n']]


In [4]:
c[0:,:1]

array([['1'],
       ['3']], dtype='<U11')

In [9]:
c[1]

array(['3', '4', 'n'], dtype='<U11')

In [10]:
c[0:]

array([['1', '2', '3'],
       ['3', '4', 'n']], dtype='<U11')

In [11]:
c[1:]

array([['3', '4', 'n']], dtype='<U11')

In [12]:
c[:1]

array([['1', '2', '3']], dtype='<U11')

In [13]:
c[:0]

array([], shape=(0, 3), dtype='<U11')

In [16]:
c[0:1]

array([['1', '2', '3']], dtype='<U11')

# Numpy array initialiation

In [39]:
type(c)

numpy.ndarray

In [40]:
type(a)

numpy.ndarray

In [44]:
a[1:2]

array([2])

In [23]:
k=np.zeros((3,4))
print(k)
#np.zeros((rows,columns))
print(k[0:1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]]


In [24]:
a=np.array([1,2,3])

In [25]:
a[0:1]

array([1])

In [26]:
a[0:2]

array([1, 2])

In [56]:
b=np.arange(10,25,1)
b
#arange(start,end,increment)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
b=np.linspace(5,15,10)
b

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [28]:
# filling same number in array of x X y
#full((row,col),element to filled)
c=np.full((3,4),4)
c

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [66]:
# randomising array
d=np.random.random((3,4))

In [67]:
d

array([[0.61915134, 0.040439  , 0.13383611, 0.23214111],
       [0.84790848, 0.69801647, 0.97248757, 0.94589841],
       [0.25849902, 0.30881368, 0.91230328, 0.24937591]])

# accessing the array

In [30]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
print(a.shape)
#np.array.shape

(2, 3)


In [40]:
a.shape=(3,2)

In [41]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a[0][0]=8
a

array([[8, 2],
       [3, 4],
       [5, 6]])

In [47]:
print(a.shape[0]),print(a.shape[1])

3
2


(None, None)

In [48]:
n=np.arange(24)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [91]:
print(n.size)

24


In [49]:
k=np.array([i for i in range(4)])
print(k.shape)

(4,)


In [95]:
k.shape=(2,2)
k

array([[1, 2],
       [3, 4]])

In [100]:
n.size

24

In [101]:
n.shape=(4,6)

In [102]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [107]:
b=np.linspace(5,7,11)
b.dtype

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ])

# Numpy array mathematics 

In [108]:
# addition using numpy
np.sum([i for i in range(10)])

45

In [109]:
np.sum([10,20])

30

In [110]:
a,b=10,20
np.sum([a,b])

30

In [117]:
a=np.array([6,4])
np.sum(a)

10

In [118]:
b=[2,3]
print(np.sum([a,b]))
print(np.subtract(a,b))

15
[4 1]


In [120]:
print(np.sum([a,b],axis=0))

[8 7]


In [121]:
print(np.sum([a,b],axis=1))

[10  5]


In [5]:
import numpy as np
np.sum([[2,3],[8,4]],axis=1)

array([ 5, 12])

In [7]:
a=np.array([2,3])
b=np.array([8,4])
np.sum([a,b],axis=1)

array([ 5, 12])

In [10]:
a=[2,3]
b=[8,4]
np.sum([a,b],axis=1)

array([ 5, 12])

In [51]:
print(np.divide([10,20],[5,4]))

[2. 5.]


In [14]:
print(np.sin(a))

[0.90929743 0.14112001]


In [24]:
k=print(np.cos(a))
print(np.sqrt(a))

[ 0.54030231 -0.41614684 -0.65364362]
[1.         1.41421356 2.        ]


# Array  Comparison

In [19]:
# element wise comparison
import numpy as np
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]
np.equal(a,b)

array([False, False,  True])

In [21]:
k=np.equal(a,c)

In [22]:
k

array([ True,  True,  True])

In [23]:
print('the values of k[1] is',k[1])

the values of k[1] is True


In [25]:
# Array wise Comparison
print(np.array_equal(a,b))

False


In [26]:
print(np.array_equal(a,c))

True


In [34]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.median(a))

21
3.5
1
6
1.707825127659933
3.5


In [35]:
print(np.corrcoef(a))

[[1. 1.]
 [1. 1.]]


# Concept of broadcasting

In [56]:
import numpy as np
np.linspace(4,6,5)

array([4. , 4.5, 5. , 5.5, 6. ])

In [57]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5]])
print(a)
print(b)
print(np.sum([a,b],axis=0))
print(np.sum([a,b]))

[[1 2 3]
 [4 5 6]]
[[3 4 5]]
[[ 4  6  8]
 [ 7  9 11]]
[[ 4  6  8]
 [ 7  9 11]]


In [ ]:
print(np.subtract(a,b))

# Indexing and Slicing in arrays

In [61]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
a

[1 2 3]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
print(a[:1,:1])

[[1]]


In [63]:
print(a[:2,:1][0])

[1]


In [64]:
a[0][1]
b=a

In [65]:
for i in range(len(a)):
    for j in range(len(a)):
        print(a[i][j]+b[i][j],end=' ')

2 4 6 8 10 12 14 16 18 

In [66]:
a[:1,:2]

array([[1, 2]])

# Array Manipulation

In [67]:
# Concatenating two arrays together
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[6,7,8]])
np.concatenate([a,b],axis=0)


array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
print(np.concatenate([a,b],axis=1))

[[1 2 3 3 4 5]
 [4 5 6 6 7 8]]


In [69]:
# vstack
print(np.stack((a,b),axis=0))

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [6 7 8]]]


In [70]:
# vstack and hstack
print(np.stack((a,b),axis=1))

[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [6 7 8]]]


In [71]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.stack((a,b),axis=0))
print(np.stack((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [72]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[6,7,8]])
print('Simple stack')
print(np.stack((a,b),axis=0))
print('Horizontal stack')
print(np.hstack((a,b)))
print('vertical stack')
print(np.hstack((a,b)))
print('Horizontal concatenate')
print(np.concatenate([a,b],axis=0))
print('vertical concatenate')
print(np.concatenate([a,b],axis=1))

Simple stack
[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [6 7 8]]]
Horizontal stack
[[1 2 3 2 3 4]
 [4 5 6 6 7 8]]
vertical stack
[[1 2 3 2 3 4]
 [4 5 6 6 7 8]]
Horizontal concatenate
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [6 7 8]]
vertical concatenate
[[1 2 3 2 3 4]
 [4 5 6 6 7 8]]


In [73]:
print('Column stack')
print(np.column_stack((a,b)))

Column stack
[[1 2 3 2 3 4]
 [4 5 6 6 7 8]]


In [74]:
print(a)

[[1 2 3]
 [4 5 6]]


In [75]:
print(np.split(a,2,0))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [76]:
k=print(np.split(a,3,1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [8]:
print(np.split(a,[1,2],0))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [15]:
# Numpy vs List:Memory size
import numpy as np
import sys

#define a list
l=range(1000)
print(l)
print('Size of a list :',sys.getsizeof(l)*len(l))

# define a numpy array
a=np.arange(1000)
print('size of array: ',a.size*a.itemsize)

range(0, 1000)
Size of a list : 48000
size of array:  4000


In [20]:
# Numpy vs List :Speed
import time
def using_list():
    t1=time.time()# Starting/Initial time
    x=range(10000)
    y=range(10000)
    z=[x[i]+y[i] for i in x]
    return time.time()-t1


def using_Numpy():
    t1=time.time()
    a=np.arange(10000)
    b=np.arange(10000)
    z=a+b
    return time.time()-t1

list_time=using_list()
numpy_time=using_Numpy()
print(list_time,numpy_time)

0.010002613067626953 0.0
